# Generated by Django 4.2.14 on 2024-07-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('recipe_description', models.TextField()),
                ('image', models.ImageField(upload_to='recipe/')),
                ('composition', models.TextField(blank=True, default='Will be added soon', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipe.category')),
            ],
            options={
                'verbose_name_plural': 'recipes',
                'ordering': ('recipe_title',),
            },
        ),
    ]
